APP_NAME: lokalise_service
APP_PORT: 5000

DB_NAME: lokalise_db
DB_HOST: localhost
DB_PORT: 5432
DB_USERNAME: my_username
DB_PASSWORD: foo
DB_POOL_SIZE: 50
JDBI_LOG_LEVEL: DEBUG
USE_HIKARI_DB_POOL: true

CORS_ALLOW_ORIGIN: http://localhost:3000
CORS_ALLOW_HEADERS: Accept,Authorization,Content-Type,Country-Code,Client-ID,Pass-Key
CORS_ALLOW_CREDENTIALS: true
CORS_REQUEST_METHOD: GET,PUT,POST,DELETE

AWS_REGION: ap-southeast-1
AWS_S3_BUCKET: your-bucket-name
AWS_ACCESS_KEY: your-access-key
AWS_SECRET_KEY: your-secret-key
AWS_S3_PRESIGN_URL_EXPIRATION_IN_DAYS: 5
